baseURL = "https://erazeunavez.fr/"
title = "Legacy Code"

theme = "hextra"

locale = "fr-FR"
defaultContentLanguage = "fr"

[params.footer]
enable = true
displayPoweredBy = true
displayCopyright = true
