name: Build Hugo site

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "publish"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HUGO_VERSION: 0.165.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          fi

      - name: Check Hugo version
        run: hugo version

      - name: Build site
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "https://erazeunavez.fr/"

      - name: Publish generated site
        run: |
          cd public

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b publish

          git add .
          git commit -m "Build ${GITHUB_SHA}"

          git push --force \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git \
            publish
